
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINESleftTIMESDIVrightUMINUSrightPOWDIV LPAREN MINES NUMBER PLUS POW RPAREN TIMESstatement : exprexpr : expr PLUS expr\n| expr MINES expr\n| expr TIMES expr\n| expr DIV exprexpr : expr POW exprexpr : LPAREN expr RPARENexpr : NUMBERexpr : MINES expr %prec UMINUS'
    
_lr_action_items = {'LPAREN':([0,3,4,6,7,8,9,10,],[4,4,4,4,4,4,4,4,]),'NUMBER':([0,3,4,6,7,8,9,10,],[5,5,5,5,5,5,5,5,]),'MINES':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,],[3,7,3,3,-8,3,3,3,3,3,-9,7,-2,-3,-4,-5,-6,-7,]),'$end':([1,2,5,11,13,14,15,16,17,18,],[0,-1,-8,-9,-2,-3,-4,-5,-6,-7,]),'PLUS':([2,5,11,12,13,14,15,16,17,18,],[6,-8,-9,6,-2,-3,-4,-5,-6,-7,]),'TIMES':([2,5,11,12,13,14,15,16,17,18,],[8,-8,-9,8,8,8,-4,-5,-6,-7,]),'DIV':([2,5,11,12,13,14,15,16,17,18,],[9,-8,-9,9,9,9,-4,-5,-6,-7,]),'POW':([2,5,11,12,13,14,15,16,17,18,],[10,-8,10,10,10,10,10,10,10,-7,]),'RPAREN':([5,11,12,13,14,15,16,17,18,],[-8,-9,18,-2,-3,-4,-5,-6,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expr':([0,3,4,6,7,8,9,10,],[2,11,12,13,14,15,16,17,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expr','statement',1,'p_statement_expr','main.py',64),
  ('expr -> expr PLUS expr','expr',3,'p_expr_binop','main.py',70),
  ('expr -> expr MINES expr','expr',3,'p_expr_binop','main.py',71),
  ('expr -> expr TIMES expr','expr',3,'p_expr_binop','main.py',72),
  ('expr -> expr DIV expr','expr',3,'p_expr_binop','main.py',73),
  ('expr -> expr POW expr','expr',3,'p_expr_pow','main.py',94),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','main.py',108),
  ('expr -> NUMBER','expr',1,'p_expr_number','main.py',112),
  ('expr -> MINES expr','expr',2,'p_expr_uminus','main.py',116),
]
